/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DcaExecutor: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "Cancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token1Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token2Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "swapStartTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "numberOfSwaps",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "Executed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token1Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token2Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token2Amount",
              type: "uint256",
            },
          ],
          name: "Swapped",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "fromExecutor",
              type: "bool",
            },
          ],
          name: "cancelDcaRequest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "dcaRequests",
          outputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token1",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token2",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "token1InitialAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token1CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token2CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startTimestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numberOfSwaps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastExecutionTimestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "executeSwap",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "receivers",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "token1",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token2",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "numberOfSwaps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startTimestamp",
              type: "uint256",
            },
          ],
          name: "submitDcaRequest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {
    DcaExecutor: {
      address: "0x64EA27E2985F03B0Cac385EeDC678bfEdECDC6D5",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "Cancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "Completed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token1Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token2Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "swapStartTime",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "numberOfSwaps",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token1Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "token2Address",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "token2Amount",
              type: "uint256",
            },
          ],
          name: "Swapped",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "activeRequestsLength",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "cancelDcaRequest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "completedRequestsLength",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "dcaRequests",
          outputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token1",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token2",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "token1InitialAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token1CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token2CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startTimestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numberOfSwapsToExecute",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numberOfSwapsExecuted",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastExecutionTimestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "dcaRequestsCompleted",
          outputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token1",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token2",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "token1InitialAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token1CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "token2CurrentAmount",
              type: "uint256",
            },
            {
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startTimestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numberOfSwapsToExecute",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numberOfSwapsExecuted",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastExecutionTimestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "executeSwap",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "receivers",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IERC20",
              name: "token1",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "token2",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "token1Amount",
              type: "uint256",
            },
            {
              internalType: "contract ISwapRouter02",
              name: "router",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "numberOfSwaps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "swapExecutionPeriod",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startTimestamp",
              type: "uint256",
            },
          ],
          name: "submitDcaRequest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
